[general]
import = [
  "~/.config/alacritty/tokyo-night.toml",
  "~/.config/alacritty/jetbrains.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 11

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
decorations = "None"

[window.padding]
x = 5
y = 5

[terminal.shell]
program = "tmux"
args = ["new", "-A", "-s", "dsg"]
