#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
PACKAGES="packages.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --quiet --recursive

sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  --base-directory "${BASEDIR}" \
  --config-file "${PACKAGES}" \
  --plugin-dir dotbot-apt \
  "${@}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  --base-directory "${BASEDIR}" \
  --config-file "${CONFIG}" \
  --plugin-dir dotbot-flatpak \
  "${@}"
