#!/bin/bash

DOTFILES_PATH="$HOME/.dotfiles"

fpath=(~/.zsh/completions $fpath)

# Source Prezto
if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  # shellcheck disable=SC1090
  source "$HOME/.zprezto/init.zsh"
fi

unsetopt nomatch

# shellcheck disable=SC1090
source "${DOTFILES_PATH}/shell/alias.sh"

# shellcheck disable=SC1090
source "${DOTFILES_PATH}/shell/env.sh"

# shellcheck disable=SC1090
source "${DOTFILES_PATH}/shell/functions.sh" || true

stty -ixon
prompt off
eval "$(starship init zsh)"

autoload zcalc
autoload -U +X compinit && compinit

source $HOME/.asdf/asdf.sh
eval "$(thefuck --alias)"
eval "$(zoxide init zsh)"
