export EDITOR='nvim'
export VISUAL='nvim'

export MANPAGER='nvim +Man!'

export PIP_REQUIRE_VIRTUALENV=true
export ERL_AFLAGS="-kernel shell_history enabled"
export GOPATH="$HOME/.go"
export GOBIN="$GOPATH/bin"
export AWS_SSO_SESSION_NAME="syncron-sso"

export ZSH_CACHE_DIR="$HOME/.cache/zinit"

DOTFILES_PATH="$HOME/.dotfiles"
SCRIPTS_PATH="$HOME/Projects/personal/scripts"

PATH="$GOPATH/bin:$PATH"
PATH="$HOME/.krew/bin:$PATH"
# PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"
PATH="$SCRIPTS_PATH/bin:$PATH"

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"

# Load completions
fpath=($ZSH_CACHE_DIR/completions $fpath)

autoload -Uz compinit && compinit

zinit light Aloxaf/fzf-tab
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions
zinit light MichaelAquilina/zsh-you-should-use

# Add in snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::aws
zinit snippet OMZP::kubectl
zinit snippet OMZP::kubectx
zinit snippet OMZP::helm
zinit snippet OMZP::command-not-found
zinit snippet OMZP::python
zinit snippet OMZP::tldr
zinit snippet OMZP::terraform
zinit ice as"completion"
zinit snippet OMZP::terraform/_terraform

zinit cdreplay -q

# Keybindings
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region
bindkey "\et" tldr-command-line
WORDCHARS='~!#$%^&*(){}[]<>?.+;-_\|=@`'

# Line editor
unsetopt flow_control  # disable ^S / ^Q
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^S' edit-command-line

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lhA'
alias cdd='cd -'
alias cdf='cd $(fd -t d | fzf)'
alias cdgr='cd $(git rev-parse --show-toplevel)'
alias aws-login='env -u AWS_CONFIG_FILE -u AWS_PROFILE -u AWS_SHARED_CREDENTIALS_FILE aws sso login --sso-session $AWS_SSO_SESSION_NAME'
alias aws-profile='export AWS_PROFILE="$(aws configure list-profiles | fzf --height=5)";echo "${AWS_PROFILE:-no profile}"'
alias aws-region='export AWS_DEFAULT_REGION=$(echo "eu-west-1\nus-east-1\nap-northeast-1\nap-south-1\nap-southeast-1"  | fzf --height=5);echo "${AWS_DEFAULT_REGION:-no region}"'
alias gsh='git show'
alias gd='git diff'
alias gds='git diff --staged'
alias gu='git pull'
alias gs='git status --short'
alias gl='git log --graph --all --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n"'
alias _='sudo'
alias :q='exit'
alias q='exit'
alias reload='source $HOME/.zshrc'
alias ssh='TERM=xterm-color ssh'
alias rm!='rm -rfv'
alias cdtmp='cd `mktemp -d`'
alias cat='batcat -pp'
alias dco='docker compose'
alias dotinstall="~/.dotfiles/install"
alias updateall='sudo apt update && sudo apt full-upgrade -V && flatpak update'
alias fd='fdfind'
alias xc='xclip -selection clipboard'
alias xp='xsel -ob'
alias .xp='. <(xp)'
alias notes='cd $HOME/obsidian && nvim'
alias now='date +"%T"'
alias today='date +"%d-%m-%Y"'
alias pathls='echo -e ${PATH//:/\\n}'
alias ports='sudo lsof -i4 -P -n | grep LISTEN'
alias ap='ansible-playbook'
alias k='kubectl'
alias tt='ttrack'

export LS_COLORS="di=01;34:ln=01;35:so=01;32:pi=01;33:ex=31:bd=34;46\
:cd=34;43:su=30;41:sg=30;46:ow=30;42:tw=30;43"

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':completion:*:*:ssh:*:*' known-hosts-files ~/.ssh/known_hosts
zstyle ':completion:*:*:make:*' tag-order 'targets'
zstyle ':fzf-tab:complete:ls:*' fzf-preview 'ls --color=always --width=$FZF_PREVIEW_COLUMNS $realpath'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color=always $realpath'
zstyle ':fzf-tab:complete:batcat:*' fzf-preview 'ls --color=always $realpath'
zstyle ':fzf-tab:*' switch-group '<' '>'

eval "$(mise activate zsh)"
eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/zen.toml)"
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"
