alias ll='ls -l'
alias la='ls -lA'
alias cdd='cd -'
alias cdf='cd $(fd -t d | fzf)'
alias cdgr='cd $(git rev-parse --show-toplevel)'
alias aws-login='aws sso login --sso-session $AWS_SSO_SESSION_NAME'
alias gt='git tree'
alias gtt='git --no-pager tree -n5'
alias gsh='git show --ext-diff'
alias _='sudo'
alias :q='exit'
alias q='exit'
alias reload='source $HOME/.zshrc'
alias ssh='TERM=xterm-color ssh'
alias vpn='sudo openvpn ~/.vpn/openvpn-config/SyncronVPN-other.ovpn'
alias vpn-all='sudo openvpn ~/.vpn/openvpn-config/SyncronVPNAllTraffic-other.ovpn'
alias rm!='rm -rfv'
alias cdtmp='cd `mktemp -d`'
alias cat='bat -pp'
alias bat='bat'
alias dco='docker compose'
alias dotinstall="~/.dotfiles/install"
alias ls='ls --color=auto'
alias fd='fdfind'
alias xc='xclip -selection clipboard'
alias xp='xsel -ob'
alias aws-profile='export AWS_PROFILE="$(aws configure list-profiles | fzf --height=10)";echo "${AWS_PROFILE:-no profile}"'
alias aws-region="export AWS_DEFAULT_REGION=\"\$(aws account list-regions | jq -r '.Regions[] | select(.RegionOptStatus == \"ENABLED_BY_DEFAULT\") | .RegionName' | fzf --height=10)\";echo \"\${AWS_DEFAULT_REGION:-no region}\""
alias notes='cd $HOME/obsidian && nvim'
alias now='date +"%T"'
alias today='date +"%d-%m-%Y"'
alias pathls='echo -e ${PATH//:/\\n}'
alias ports='sudo lsof -i4 -P -n | grep LISTEN'
