alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lhA'
alias cdd='cd -'
alias cdf='cd $(fd -t d | fzf)'
alias cdgr='cd $(git rev-parse --show-toplevel)'
alias aws-login='env -u AWS_CONFIG_FILE -u AWS_PROFILE -u AWS_SHARED_CREDENTIALS_FILE aws sso login --sso-session $AWS_SSO_SESSION_NAME'
alias aws-profile='export AWS_PROFILE="$(aws configure list-profiles | fzf --height=5)";echo "${AWS_PROFILE:-no profile}"'
alias aws-region='export AWS_DEFAULT_REGION=$(echo "eu-west-1\nus-east-1\nap-northeast-1\nap-south-1\nap-southeast-1"  | fzf --height=5);echo "${AWS_DEFAULT_REGION:-no region}"'
alias gsh='git show'
alias gd='git diff'
alias gds='git diff --staged'
alias gu='git pull'
alias gs='git status --short'
alias gl='git log --graph --all --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n"'
alias _='sudo'
alias :q='exit'
alias q='exit'
alias reload='source $HOME/.zshrc'
alias ssh='TERM=xterm-color ssh'
alias rm!='rm -rfv'
alias cdtmp='cd `mktemp -d`'
alias cat='batcat -pp'
alias dco='docker compose'
alias dotinstall="~/.dotfiles/install"
alias updateall='sudo apt update && sudo apt full-upgrade -V && flatpak update'
alias fd='fdfind'
alias xc='xclip -selection clipboard'
alias xp='xsel -ob'
alias .xp='. <(xp)'
alias notes='cd $HOME/obsidian && nvim'
alias now='date +"%T"'
alias today='date +"%d-%m-%Y"'
alias pathls='echo -e ${PATH//:/\\n}'
alias ports='sudo lsof -i4 -P -n | grep LISTEN'
alias ap='ansible-playbook'
alias k='kubectl'
alias tt='ttrack'
