alias ls='eza --icons=always'
alias ll='ls -l'
alias la='ls -lA'
alias cdd='cd -'
alias cdf='cd $(fd -t d | fzf)'
alias cdgr='cd $(git rev-parse --show-toplevel)'
alias aws-login='aws sso login --sso-session $AWS_SSO_SESSION_NAME'
alias aws-profile='export AWS_PROFILE="$(aws configure list-profiles | fzf --height=10)";echo "${AWS_PROFILE:-no profile}"'
alias gsh='git show'
alias gd='git diff'
alias gds='git diff --staged'
alias gu='git pull'
alias gs='git status --short'
alias gl='git log --graph --all --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n"'
alias _='sudo'
alias :q='exit'
alias q='exit'
alias reload='source $HOME/.zshrc'
alias ssh='TERM=xterm-color ssh'
alias vpnc='openvpn3 session-start --config ~/.vpn/openvpn-config/SyncronVPN-other.ovpn'
alias vpnd='openvpn3 session-manage --disconnect --config ~/.vpn/openvpn-config/SyncronVPN-other.ovpn'
alias rm!='rm -rfv'
alias cdtmp='cd `mktemp -d`'
alias cat='bat -pp'
alias dco='docker compose'
alias dotinstall="~/.dotfiles/install"
alias fd='fdfind'
alias xc='xclip -selection clipboard'
alias xp='xsel -ob'
alias .xp='. <(xp)'
alias notes='cd $HOME/obsidian && nvim'
alias now='date +"%T"'
alias today='date +"%d-%m-%Y"'
alias pathls='echo -e ${PATH//:/\\n}'
alias ports='sudo lsof -i4 -P -n | grep LISTEN'
alias ap='ansible-playbook'
alias k='kubectl'
alias tt='ttrack'
